name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v4
        with:
          github_user_name: HengHoursan
          outputs: output/github-contribution-grid-snake.svg
          color_snake: "#00b4d8"
          color_dots: "#caf0f8"
      - name: Push to output directory
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output
          git commit -m "Generate snake"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
